menu_items = {
    "Check Vote Statistics": "get_total_votes_for_eligible_validator",
    "Create New Wallet": "new_validator",
    "Çreate New Account": "create_account",
    "Lock Map": "locked_map",
    "Unlock Map": "unlock_map",
    "Get Account Non Voting Locked Maps": "get_account_nonvoting_locked_gold",
    "Get Account Total Locked Maps": "get_account_total_locked_gold",
    "Get Active Votes for Validator by Account": "get_active_votes_for_validator_by_account",
    "Get Pending Withdrawals": "get_pending_withdrawals",
    "Withdraw Map": "withdraw_map",
    "Register Validator": "register",
    "De-Register Validator": "deregister",
    "Revert Register Validator": "revert_register",
    "Authorise Signer": "authorise_validator_signer",
    "Vote": "vote",
    "Activate Votes": "activate_votes",
    "Revoke Pending Votes": "revoke_pending_votes",
    "Revoke Active Votes": "revoke_active_votes",
    "Join Network (Sync)": "join_network",
    "Make ECDSA Signature From Signer": "make_ECDSA_signature_from_signer",
    "Make BLS Proof Of Possession From Signer": "make_BLS_proof_of_possession_from_signer",
    "Get Balance": "get_balance",
    "Get Current Block Number": "get_block_number",
    "Get Validator Reward Info": "getValidatorRewardInfo",
    "Check if Elected": "check_if_selected",
    "Private Key From Keystore": "find_pk",
    "Setup atlasNode Service": "setup_atlas_node_service",
    "Show Node Logs": "show_tail",
}
