menu_items = {
    "List / Update Input Data": "display_and_update_env",
    "Atlas Version Info": "get_atlas_version",
    "Check Vote Statistics": "get_total_votes_for_eligible_validator",
    "Create New Keystore Address": "new_account",
    "Create New Account": "create_account",
    "Lock Map": "locked_map",
    "Unlock Map": "unlock_map",
    "Get Account Non Voting Locked Maps": "get_account_nonvoting_locked_gold",
    "Get Account Total Locked Maps": "get_account_total_locked_gold",
    "Get Active Votes for Validator by Account": "get_active_votes_for_validator_by_account",
    "Get Pending Withdrawals": "get_pending_withdrawals",
    "Withdraw Map": "withdraw_map",
    "Register Validator": "register",
    "De-Register Validator": "deregister",
    "Revert Register Validator": "revert_register",
    "Authorise Signer": "authorise_validator_signer",
    "Vote": "vote",
    "Activate Votes": "activate_votes",
    "Revoke Pending Votes": "revoke_pending_votes",
    "Revoke Active Votes": "revoke_active_votes",
    "Join Network (Sync)": "join_network",
    "Make ECDSA Signature From Signer": "make_ECDSA_signature_from_signer",
    # "Make BLS Proof Of Possession From Signer": "make_BLS_proof_of_possession_from_signer",
    "Generate Signer Proof": "generate_signer_proof",
    "Authorise Validator Signer By Signature": "authorise_validator_signer_by_signature",
    "Get Balance": "get_balance",
    "Block Number of Network from RPC": "get_block_number",
    "Block Number of Local Node": "eth_blockNumber",
    "Compare Local / RPC Block Number": "compare_block_numbers",
    "Get Local Peer Count": "admin_peers_length",
    "Get Validator Reward Info": "get_validator_reward_info",
    "Get Validator Information": "get_validator",
    "Check if Elected": "check_if_selected",
    "Private Key From Keystore": "find_pk",
    "Setup atlasNode Service": "setup_atlas_node_service",
    "Transfer Map using Keystore": "transfer",
    "Get Epoch Data": "get_epoch_data",
    "Show Node Logs": "show_tail",
}
