name_map = {
    "name": "type of address, i.e. `validator`",
    "target": "the target validator address to check",
    "lockedNum": "amount of MAP to lock",
    "mapValue": "the amount of Map",
    "withdrawIndex": "withdraw index from pending withdrawals",
    "signerPriv": "Signer Private Key",
    "validator": "Validator Address",
    "commission": "Commission of validator in %",
    "voteNum": "amount of MAP to vote with",
    "datadir": "Data Directory",
    "miner.validator": "Validator Address to mine",
    "unlock": "Address to unlock to",
    "syncmode": "Syncing mode required",
    "port": "Port to run Node on",
    "default_address": "Enter address to check",
}
